stage('Build and Push Docker Image') {
  environment {
    DOCKER_IMAGE = "matt-fibonnacci/demo-java-app:${build_version}"
    REGISTRY_CREDENTIALS = credentials('dockerhub')
  }
  steps {
    script {
      sh 'cd demo-java-app && docker build -t ${DOCKER_IMAGE} .'

      def dockerImage = docker.image("${DOCKER_IMAGE}")

      docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
        dockerImage.push()
      }
    }
  }
}
